receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource/add_labels:
    attributes:
      - key: service.name
        from_attribute: service
        action: insert
  attributes/add_service_label:
    actions:
      - key: service
        value: aspire-app
        action: insert
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/aspire:
    endpoint: ${env:ASPIRE_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
        insecure: ${env:ASPIRE_INSECURE}
        insecure_skip_verify: true # Required in local development because cert is localhost and the endpoint is host.docker.internal
  prometheus:
    endpoint: 0.0.0.0:8889
  loki:
    endpoint: ${env:LOKI_ENDPOINT}
    tls:
      insecure: ${env:ASPIRE_INSECURE}
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
    logs:
      receivers: [otlp]
      processors: 
        - attributes/add_service_label
        - resource/add_labels
        - batch
      exporters: 
        - otlp/aspire
        - loki

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlp/aspire
        - prometheus

