global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'aspire-monitoring'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:7284']
      
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
